### ISSUE TITLE
Support for Bluetooth without Jabra Link

### ISSUE THREAD

**Issue by mjacquet** [balansse/google-meet-jabra#13]
Hey,
I am using Jabra Evolve2 85 without the Dongle, and would love to use this!
I see in the readme that it is potential future feature so I just created this to get potentially some visibility and to be bale to track this.
Thanks!

**Comment by balansse** [comment]
Unfortunately there is no Jabra SDK available to get access to the device specific features like busy light without going through the Jabra Link dongle or wired, so it would be impossible for now.

I noticed that Evolve2 85 would automatically turn on busy light when it detects a call - and any app that requires mic triggers call mode if connected through bluetooth. You can configure the busy light call behavior using Jabra Sound+ app on your smartphone.
