### ISSUE TITLE
Linux?

### ISSUE THREAD

**Issue by piec** [balansse/google-meet-jabra#14]
Hi,

Have you been able to use it under Linux?
I tried google chrome / chromium and I can select the device and click the "connect" button but then the control doesn't work. I'm using a Jabra 510 usb.

Also I don't know which logs to check in order to debug this.
Do you have more information?

Thanks :)

**Comment by jimmysjolund** [comment]
I have the same issue with Fedora 37 and Jabra Evolve 40. I connect and it still say Not connected, and the next time it states "Paired" but will not connect.

**Comment by st1dev** [comment]
Are you guys using (native) BlueTooth connections between computer and the device?
It sounds a bit like the behaviour you get when using the BT device profile, rather than the USB HID protocol.
The Jabra SDK libraries only work over USB. And connected via BT, there is no mute command defined in the protocol...

**Comment by jimmysjolund** [comment]
I connect via the USB where the buttons are. I have the same experience in Fedora 38.

**Comment by piec** [comment]
Hi, I'm using USB too

**Comment by dhiller** [comment]
Same here, Linux Fedora 38 with Google Chrome Stable, using Jabra 410 USB

**Comment by piec** [comment]
In my case the issue was not related to this extension (also the extension was not required to make it work).
The issue was on the permissions of the hidraw device.
I fixed it like this:
<pre>
$ groups
[...] <b>input</b> [...]

$ lsusb | grep -i jabra
Bus 003 Device 034: ID <b>0b0e:0420</b> GN Netcom Jabra SPEAK 510

# create this file:
$ cat /etc/udev/rules.d/50-jabra.rules
SUBSYSTEM=="hidraw", ATTRS{idVendor}=="<b>0b0e</b>", ATTRS{idProduct}=="<b>0420</b>", MODE="0660", GROUP="<b>input</b>"

# unplug, replug usb device

$ ls -la /dev/hidraw*
[...]
crw-<b>rw-</b>--- 1 root <b>input</b> 240, 6 Oct 30 11:53 /dev/hidraw6
[...]
</pre>
Notes:
* My user belongs to the `input` group, you'll probably want to use `plugdev` in ubuntu.
* Adapt product & vendor ids to your device

Related: https://developer.chrome.com/articles/hid/#dev-tips
