### ISSUE TITLE
Evolve2 85 not working

### ISSUE THREAD

**Issue by stiliajohny** [balansse/google-meet-jabra#4]
Hi 

I am using the Evolve2 85 and even after following the instructions is not working as expected. 

no red light or mute is working when I am on a Meet call. 

Any troubleshooting steps ?

**Comment by balansse** [comment]
Do you use the included Jabra Link USB dongle to connect your headset?

**Comment by stiliajohny** [comment]
Hi 
Yes I used the Dongle to connect 
I try on macos

**Comment by balansse** [comment]
I have a Jabra Evolve2 85 and I don't notice any issues. Do you have Jabra Direct app installed on your mac?

**Comment by stiliajohny** [comment]
> Do you have Jabra Direct app installed on your mac? 

Yes

**Comment by balansse** [comment]
Then I see no reason why it wouldn't work - can you check the console, are
there any error messages there?
