### ISSUE TITLE
Support for Jabra Talk 45 Bluetooth Device

### ISSUE THREAD

**Issue by ralphbac** [balansse/google-meet-jabra#7]
Hi,

This is not an issue but more of a question. I just recently bought Jabra Talk 45 and trying to mute/unmute Google Meet using the device but to no avail. I know that this extension does not support Bluetooth devices yet, but is this something we can support soon?

By the way, thank you for this initiative. Really helped a lot of Jabra users out there! :)

**Comment by kolbeck** [comment]
The Jabra library used in this extension only supports USB connected devices, so it would depend on Jabra providing this feature or making a custom implementation.
